pipeline {
    agent any

    environment {
        AWS_REGION = 'ap-southeast-2'
        AWS_DEFAULT_REGION = 'ap-southeast-2'
        TF_DIR = '02_EKS_terraform-manifests'
        ENV = 'dev'
    }

    stages {

        stage('Clean Workspace') {
            steps {
                deleteDir()
            }
        }

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Clean Terraform Cache') {
            steps {
                dir("${TF_DIR}") {
                    sh '''
                    rm -rf .terraform
                    rm -f .terraform.lock.hcl
                    '''
                }
            }
        }

        stage('Terraform Format Check') {
            steps {
                dir("${TF_DIR}") {
                    sh 'terraform fmt -recursive'
                    sh 'terraform fmt -check -recursive'
                }
            }
        }

        stage('Terraform Init') {
            steps {
                dir("${TF_DIR}") {
                    sh """
                    terraform init \
                      -reconfigure \
                      -upgrade \
                      -backend-config="bucket=jenkins-terraform-statefile-1807" \
                      -backend-config="key=${ENV}/eks/terraform.tfstate" \
                      -backend-config="region=${AWS_REGION}"
                    """
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                dir("${TF_DIR}") {
                    sh 'terraform validate'
                }
            }
        }

        stage('Security Scan') {
            steps {
                dir("${TF_DIR}") {
                    sh 'checkov -d . || true'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir("${TF_DIR}") {
                    sh 'terraform plan -out=tfplan'
                }
            }
        }

        stage('Debug AWS') {
            steps {
                sh '''
                which aws
                aws --version
                aws sts get-caller-identity
                '''
            }
        }

        stage('Approval') {
            when {
                expression {
                    env.ENV == 'prod'
                }
            }
            steps {
                timeout(time: 10, unit: 'MINUTES') {
                    input message: "Approve deployment to ${ENV}?", ok: "Approve"
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir("${TF_DIR}") {
                    sh 'terraform apply -auto-approve tfplan'
                }
            }
        }

        stage('Configure Kubeconfig') {
            steps {
                sh """
                mkdir -p ~/.kube
                aws eks update-kubeconfig \
                    --region ${AWS_REGION} \
                    --name retail-dev-eksdemo1
                """
            }
        }
    }

    post {
        success {
            echo "✅ Deployment to ${ENV} successful"
        }
        failure {
            echo "❌ Deployment failed"
        }
    }
}
