pipeline {
    agent any

    environment {
        AWS_REGION = 'us-east-1'
        CLUSTER_NAME = 'retail-dev-eksdemo1'
        HELM_DIR = '03_RetailStore_Helm_with_Data_Plane/01_retailstore_charts_updates/charts_base'
        NAMESPACE = 'default'
    }

    stages {

        stage('Clean Workspace') {
            steps {
                deleteDir()
            }
        }

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Configure Kubeconfig') {
            steps {
                sh '''
                mkdir -p ~/.kube
                
                aws eks update-kubeconfig \
                  --region $AWS_REGION \
                  --name $CLUSTER_NAME
                '''
            }
        }

        stage('Deploy All Helm Charts') {
            steps {
                dir("${HELM_DIR}") {
                    sh '''
                    set -e

                    echo "🚀 Deploying all microservices..."

                    for dir in */; do
                        APP=$(basename $dir)

                        echo "✅ Deploying $APP..."

                        helm upgrade --install $APP $dir \
                            --namespace $NAMESPACE \
                            --create-namespace

                        echo "⏳ Waiting for $APP rollout..."
                        kubectl rollout status deployment/$APP

                        echo "✅ $APP deployed successfully"
                    done

                    echo "🎉 All services deployed!"
                    '''
                }
            }
        }

        stage('Verify Deployment') {
            steps {
                sh '''
                echo "📦 Pods:"
                kubectl get pods

                echo "🌐 Services:"
                kubectl get svc
                '''
            }
        }
    }

    post {
        success {
            echo "✅ Full application deployed successfully"
        }
        failure {
            echo "❌ Deployment failed"
        }
    }
}
